#端口号设置：
server: 
  port: ${CMBS_QUERY_ORDER_PORT}
#注册中心设置
eureka:
  instance:
    leaseRenewalIntervalInSeconds: 10 ##心跳检测时长
    prefer-ip-address: true           ##显示IP(注册中心服务地址部分将以IP显示,而非机器名称)
  client:
    registryFetchIntervalSeconds: 5
    instanceInfoReplicationIntervalSeconds: 5
    initialInstanceInfoReplicationIntervalSeconds: 5
    serviceUrl:
      defaultZone: ${eureka_url}
#datasource数据源设置     
spring: 
    mktBusinessDatasource: 
      url: ${business_jdbc_url}
      username: ${business_jdbc_username}
      password: ${business_jdbc_password}
      type: com.alibaba.druid.pool.DruidDataSource
      driver-class-name: com.mysql.jdbc.Driver
    mktConfigDatasource: 
      url: ${config_jdbc_url}
      username: ${config_jdbc_username}
      password: ${config_jdbc_password}
      driver-class-name: com.mysql.jdbc.Driver
    cloud:
      stream:
        kafka:
          binder:
            zk-nodes: ${zookeeper_serverList}
            brokers: ${kafka_bootstrap_servers}

#mybatis：mapperLocations设置 
mybatis: 
  mapperLocations:
    - classpath*:sqlmap/*Mapper.xml
  type-aliases-package: 
     org.springboot.sample.entity
#rediscluster配置
redis:
  clusterNodes: ${redis_cluster_nodes}
  commandTimeout: ${redis_command_timeout}
  expireSeconds: ${redis_expire_seconds}

#集群编号
sequence:
  myid: 2

logging:
  level:
    org.springframework.web.servlet.DispatcherServlet: error
    com.*.mapper: error
    com.migu: error
#请求地址
resourceurl:
  orderCreateUrl: ${resourceurl_order_create}
  dataFlowGrantUrl: ${resourceurl_dataflow_grant}
  dataFlowOrderQueryUrl: ${resourceurl_dataflow_order_query}
  dataFlowGrangCallbackUrl: ${resourceurl_dataflow_grant_callback}
  contractSubscribeUrl: ${resourceurl_contract_subscribe}
  querySubscriptionUrl: ${resourceurl_query_subscription}
  grantFlowUrl: ${resourceurl_grant_flow}
  smsSendUrl: ${resourceurl_sms_send}
  queryMsisdnSectionUrl: ${resourceurl_query_msisdn_section}
  getMonthlyVote: ${resourceurl_get_monthly_vote}
  queryUserInfoUrl: ${resourceurl_query_userinfo}
  queryUserInfoByMsisdnUrl: ${resourceurl_query_userinfo_by_msisdn}
  queryUserInfoByMsisdnTempUrl: ${resourceurl_query_userinfo_by_msisdn_temp}
#总体配置
redisswitch_on: ${redisswitch_on}

#中奖公示取前N条
win_prize_size: 20

#FTP配置
ftpurl:
  tempDirectory: ${temp_directory}
  ftpIp: ${ftp_ip}
  ftpPort: ${ftp_port}
  ftpUsername: ${ftp_username}
  ftpPassword: ${ftp_password}
  ftpDirectory: ${ftp_directory}
